version: '3.7'
services:
  mysql:
    hostname: mysql
    image: mysql:5.7
    restart: always
    logging:
      driver: none
    environment:
      MYSQL_DATABASE: 'movie'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'P@ssw0rd'
      MYSQL_ROOT_PASSWORD: 'P@ssw0rd'
    ports:
      - '3306:3306'

  eurekaserver:
    hostname: eurekaserver
    build:
      context: eurekaserver
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    depends_on:
      - mysql

  eurekaclient:
    hostname: eurekaclient
    environment:
      - EUREKA_SERVER=http://eurekaserver:8761/eureka
      - MYSQL=mysql:3306
    build:
      context: eurekaclient
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - eurekaserver